apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: qa
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 9000          # port inside cluster
      targetPort: 9000  # port your app listens on   
  type: LoadBalancer